MODEL:
  NAME: 'efficientnet_v2_s'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: ''
  KEEP_CAMID_CENTROIDS: True
  PRETRAINED: True
  RESUME_TRAINING: False

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 15
  EVAL_PERIOD: 1

USE_MIXED_PRECISION: True

LOG_DIR: "logs"
REPRODUCIBLE_NUM_RUNS: 2
